Using in the docker build the cache pulled from docker hub

diff --git a/hooks/build b/hooks/build
--- a/hooks/build
+++ b/hooks/build
@@ -1,7 +1,19 @@
 #!/bin/bash
 
+if [ -z "$DOCKER_REPO" ]
+then
+  # If the varible is empty replace it with the public repository name
+  DOCKER_REPO=mattiabertorello/amazon-kinesis-agent
+fi
+
+# fetches the latest image (not failing if image is not found)
+docker pull "$DOCKER_REPO:latest" || true
+
 # https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1
 # $IMAGE_NAME var is injected into the build so the tag is correct.
-docker build --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
+docker build \
+  --pull \
+  --cache-from "$DOCKER_REPO:latest" \
+  --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
   --build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
   -t "$IMAGE_NAME" .
